openapi: 3.0.1
info:
  title: ExternalServiceAPI
  description: API Definition of ExternalServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/externalService
paths:
  /call:
    get:
      responses:
        default:
          description: Default response
