openapi: 3.0.1
info:
  title: PetStoreAPI
  description: API Definition of PetStoreAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/petstoreapi
paths:
  /query:
    get:
      parameters:
      - name: param
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
