openapi: 3.0.1
info:
  title: HondaVehicles2
  description: API Definition of HondaVehicles2
  version: 1.0.0
servers:
- url: http://localhost:8290/hondavehicles2
paths:
  /list:
    get:
      parameters:
      - name: type
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
